/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupCallbackImport } from './routes/signup-callback'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as EmailCampaignsEmailCampaignIdIndexImport } from './routes/emailCampaigns/$emailCampaignId/index'
import { Route as EmailCampaignsEmailCampaignIdMassImport } from './routes/emailCampaigns/$emailCampaignId/mass'
import { Route as EmailCampaignsEmailCampaignIdIndividualProfilerIdImport } from './routes/emailCampaigns/$emailCampaignId/individual/$profilerId'

// Create/Update Routes

const SignupCallbackRoute = SignupCallbackImport.update({
  id: '/signup-callback',
  path: '/signup-callback',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmailCampaignsEmailCampaignIdIndexRoute =
  EmailCampaignsEmailCampaignIdIndexImport.update({
    id: '/emailCampaigns/$emailCampaignId/',
    path: '/emailCampaigns/$emailCampaignId/',
    getParentRoute: () => rootRoute,
  } as any)

const EmailCampaignsEmailCampaignIdMassRoute =
  EmailCampaignsEmailCampaignIdMassImport.update({
    id: '/emailCampaigns/$emailCampaignId/mass',
    path: '/emailCampaigns/$emailCampaignId/mass',
    getParentRoute: () => rootRoute,
  } as any)

const EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute =
  EmailCampaignsEmailCampaignIdIndividualProfilerIdImport.update({
    id: '/emailCampaigns/$emailCampaignId/individual/$profilerId',
    path: '/emailCampaigns/$emailCampaignId/individual/$profilerId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup-callback': {
      id: '/signup-callback'
      path: '/signup-callback'
      fullPath: '/signup-callback'
      preLoaderRoute: typeof SignupCallbackImport
      parentRoute: typeof rootRoute
    }
    '/emailCampaigns/$emailCampaignId/mass': {
      id: '/emailCampaigns/$emailCampaignId/mass'
      path: '/emailCampaigns/$emailCampaignId/mass'
      fullPath: '/emailCampaigns/$emailCampaignId/mass'
      preLoaderRoute: typeof EmailCampaignsEmailCampaignIdMassImport
      parentRoute: typeof rootRoute
    }
    '/emailCampaigns/$emailCampaignId/': {
      id: '/emailCampaigns/$emailCampaignId/'
      path: '/emailCampaigns/$emailCampaignId'
      fullPath: '/emailCampaigns/$emailCampaignId'
      preLoaderRoute: typeof EmailCampaignsEmailCampaignIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/emailCampaigns/$emailCampaignId/individual/$profilerId': {
      id: '/emailCampaigns/$emailCampaignId/individual/$profilerId'
      path: '/emailCampaigns/$emailCampaignId/individual/$profilerId'
      fullPath: '/emailCampaigns/$emailCampaignId/individual/$profilerId'
      preLoaderRoute: typeof EmailCampaignsEmailCampaignIdIndividualProfilerIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$emailCampaignId/mass': typeof EmailCampaignsEmailCampaignIdMassRoute
  '/emailCampaigns/$emailCampaignId': typeof EmailCampaignsEmailCampaignIdIndexRoute
  '/emailCampaigns/$emailCampaignId/individual/$profilerId': typeof EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$emailCampaignId/mass': typeof EmailCampaignsEmailCampaignIdMassRoute
  '/emailCampaigns/$emailCampaignId': typeof EmailCampaignsEmailCampaignIdIndexRoute
  '/emailCampaigns/$emailCampaignId/individual/$profilerId': typeof EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$emailCampaignId/mass': typeof EmailCampaignsEmailCampaignIdMassRoute
  '/emailCampaigns/$emailCampaignId/': typeof EmailCampaignsEmailCampaignIdIndexRoute
  '/emailCampaigns/$emailCampaignId/individual/$profilerId': typeof EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$emailCampaignId/mass'
    | '/emailCampaigns/$emailCampaignId'
    | '/emailCampaigns/$emailCampaignId/individual/$profilerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$emailCampaignId/mass'
    | '/emailCampaigns/$emailCampaignId'
    | '/emailCampaigns/$emailCampaignId/individual/$profilerId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$emailCampaignId/mass'
    | '/emailCampaigns/$emailCampaignId/'
    | '/emailCampaigns/$emailCampaignId/individual/$profilerId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SignupCallbackRoute: typeof SignupCallbackRoute
  EmailCampaignsEmailCampaignIdMassRoute: typeof EmailCampaignsEmailCampaignIdMassRoute
  EmailCampaignsEmailCampaignIdIndexRoute: typeof EmailCampaignsEmailCampaignIdIndexRoute
  EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute: typeof EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SignupCallbackRoute: SignupCallbackRoute,
  EmailCampaignsEmailCampaignIdMassRoute:
    EmailCampaignsEmailCampaignIdMassRoute,
  EmailCampaignsEmailCampaignIdIndexRoute:
    EmailCampaignsEmailCampaignIdIndexRoute,
  EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute:
    EmailCampaignsEmailCampaignIdIndividualProfilerIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/login",
        "/signup-callback",
        "/emailCampaigns/$emailCampaignId/mass",
        "/emailCampaigns/$emailCampaignId/",
        "/emailCampaigns/$emailCampaignId/individual/$profilerId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup-callback": {
      "filePath": "signup-callback.tsx"
    },
    "/emailCampaigns/$emailCampaignId/mass": {
      "filePath": "emailCampaigns/$emailCampaignId/mass.tsx"
    },
    "/emailCampaigns/$emailCampaignId/": {
      "filePath": "emailCampaigns/$emailCampaignId/index.tsx"
    },
    "/emailCampaigns/$emailCampaignId/individual/$profilerId": {
      "filePath": "emailCampaigns/$emailCampaignId/individual/$profilerId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
