/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupCallbackImport } from './routes/signup-callback'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as EmailCampaignsCampaignIdImport } from './routes/emailCampaigns/$campaignId'

// Create/Update Routes

const SignupCallbackRoute = SignupCallbackImport.update({
  id: '/signup-callback',
  path: '/signup-callback',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmailCampaignsCampaignIdRoute = EmailCampaignsCampaignIdImport.update({
  id: '/emailCampaigns/$campaignId',
  path: '/emailCampaigns/$campaignId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup-callback': {
      id: '/signup-callback'
      path: '/signup-callback'
      fullPath: '/signup-callback'
      preLoaderRoute: typeof SignupCallbackImport
      parentRoute: typeof rootRoute
    }
    '/emailCampaigns/$campaignId': {
      id: '/emailCampaigns/$campaignId'
      path: '/emailCampaigns/$campaignId'
      fullPath: '/emailCampaigns/$campaignId'
      preLoaderRoute: typeof EmailCampaignsCampaignIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$campaignId': typeof EmailCampaignsCampaignIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$campaignId': typeof EmailCampaignsCampaignIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup-callback': typeof SignupCallbackRoute
  '/emailCampaigns/$campaignId': typeof EmailCampaignsCampaignIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/signup-callback'
    | '/emailCampaigns/$campaignId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SignupCallbackRoute: typeof SignupCallbackRoute
  EmailCampaignsCampaignIdRoute: typeof EmailCampaignsCampaignIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SignupCallbackRoute: SignupCallbackRoute,
  EmailCampaignsCampaignIdRoute: EmailCampaignsCampaignIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/login",
        "/signup-callback",
        "/emailCampaigns/$campaignId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup-callback": {
      "filePath": "signup-callback.tsx"
    },
    "/emailCampaigns/$campaignId": {
      "filePath": "emailCampaigns/$campaignId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
